---
- name: Start/Stop ec2 instances
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    region: us-east-1
  tasks:
    - name: "{{ state }} the {{ instance_id }} instance "
      ec2:
        instance_ids: "{{ instance_id }}"
#        instance_tags:
#                Name: "{{ instance_tag }}"
        region: '{{ region }}'
        state: "{{ state }}"
        wait: True